language: 'en'
baseDescription: Ezequiel's website
baseTitle: Ezequiel Schwartzman
avatar: /assets/avatar2.jpg
avatarDescription: A portrait of Ezequiel looking at the camera with a garden in the background
favicon: /assets/favicon.jpg
layoutComponents:
  - ArrarraNav
navigation:
  -
    title: About
    path: '/'
  -
    title: Creations
    path: '/creations'
  -
    title: Collaboration
    path: '/collaboration'
  -
    title: Notes
    path: '/notes'
  -
    title: Video Room
    path: '/video-room'
  -
    title: Availability
    path: '/availability'
  -
    title: Contact
    path: '/contact'
socialLinks:
  -
    name: GitHub
    url: https://github.com/zequez
  -
    name: YouTube
    url: https://www.youtube.com/channel/UCXhH5g4vDaci5EcqYaYv1kw
  -
    name: Telegram
    url: https://t.me/zequez

